### ISSUE TITLE
Deleting line profile on live data can lead to computation commit error with stack trace

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#1063]
Start a scan (using usim), add a line profile, delete line profile.

```
Traceback (most recent call last):
  File "/Users/user/developer/nionui/nion/ui/UserInterface.py", line 3637, in _handle_periodic
    self.on_periodic()
  File "/Users/user/developer/nionswift/nion/swift/DocumentController.py", line 474, in periodic
    super().periodic()
  File "/Users/user/developer/nionui/nion/ui/Window.py", line 372, in periodic
    self.__periodic_queue.perform_tasks()
  File "/Users/user/developer/nionutils/nion/utils/Process.py", line 43, in perform_tasks
    task()
  File "/Users/user/developer/nionswift/nion/swift/DocumentController.py", line 265, in call_soon
    self.document_model.perform_call_soon()
  File "/Users/user/developer/nionswift/nion/swift/model/DocumentModel.py", line 788, in perform_call_soon
    fn()
  File "/Users/user/developer/nionswift/nion/swift/model/DocumentModel.py", line 1666, in commit_pending_computation
    pending_computation_executor.commit()
  File "/Users/user/developer/nionswift/nion/swift/model/Symbolic.py", line 2651, in commit
    self._commit()
  File "/Users/user/developer/nionswift/nion/swift/model/Symbolic.py", line 2744, in _commit
    self.__data_item.set_xdata(self.__data_item_target.xdata)
  File "/Users/user/developer/nionswift/nion/swift/model/DataItem.py", line 1015, in set_xdata
    self.set_data_and_metadata(xdata, data_modified)
  File "/Users/user/developer/nionswift/nion/swift/model/DataItem.py", line 1258, in set_data_and_metadata
    self.__set_data_and_metadata_direct(new_data_and_metadata, data_modified)
  File "/Users/user/developer/nionswift/nion/swift/model/DataItem.py", line 1229, in __set_data_and_metadata_direct
    self.__set_data_metadata_direct(data_and_metadata.data_metadata, data_modified)
  File "/Users/user/developer/nionswift/nion/swift/model/DataItem.py", line 1205, in __set_data_metadata_direct
    self._set_persistent_property_value("data_shape", data_metadata.data_shape)
  File "/Users/user/developer/nionswift/nion/swift/model/Persistence.py", line 1064, in _set_persistent_property_value
    property = self.__properties[name]
               ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'data_shape'
```

**Comment by cmeyer** [comment]
Temporary fix here 4f54c93bc73d76ca1b2b57ff86f1429f3ed5a056, closing
