### ISSUE TITLE
Exception calculating thumbnails

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#1179]
I'm getting lots of tracebacks like the following lately:

```
Traceback (most recent call last):
File "d:\git\nionswift\nion\swift\Thumbnails.py", line 102, in recompute_data
    calculated_data = self.__get_calculated_data(ui)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "d:\git\nionswift\nion\swift\Thumbnails.py", line 88, in __get_calculated_data
    return ui.create_rgba_image(thumbnail_drawing_context, self.width, self.height)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "d:\git\nionui\nion\ui\QtUserInterface.py", line 2433, in create_rgba_image
    self.proxy.DrawingContext_paintRGBAToImage_binary(drawing_context.binary_commands, copy.copy(drawing_context.images), image_array)
File "C:\Users/Andi/Miniconda3/envs/developer-forge/Scripts/NionSwiftLauncher\bootstrap.py", line 35, in _missing
    return getattr(self.__nion_lib, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'HostLib' has no attribute 'DrawingContext_paintRGBAToImage_binary'. Did you mean: 'DrawingContext_paintRGBA_binary'?
File "C:\Users\Andi\Miniconda3\envs\developer-forge\Lib\threading.py", line 1032, in _bootstrap
    self._bootstrap_inner()
File "C:\Users\Andi\Miniconda3\envs\developer-forge\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
File "C:\Users\Andi\Miniconda3\envs\developer-forge\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
File "C:\Users\Andi\Miniconda3\envs\developer-forge\Lib\concurrent\futures\thread.py", line 92, in _worker
    work_item.run()
File "C:\Users\Andi\Miniconda3\envs\developer-forge\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
File "d:\git\nionutils\nion\utils\ThreadPool.py", line 129, in dispatch_task
    fn()
File "d:\git\nionswift\nion\swift\Thumbnails.py", line 106, in recompute_data
    traceback.print_stack()
```

Also, whenever I create a new data item, it does not get a thumbnail in DataPanel, so it looks like thumbnail calculation is just bugged. I haven't seen this anywhere else than on my system so far, but even a clean developer installation still has this problem.
So am I doing anything wrong here or is there actually a bug that only shows under certain conditions?

This is my "conda list" output from the env I use for running nionswift:

```
# packages in environment at C:\Users\Andi\Miniconda3\envs\developer-forge:
#
# Name                    Version                   Build  Channel
brotli-python             1.1.0           py312h275cf98_2    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.8.30            h56e8100_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h4389bb4_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0          nompi_py312ha036244_102    conda-forge
hdf5                      1.14.3          nompi_h2b43c12_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
imageio                   2.35.1             pyh12aca89_0    conda-forge
intel-openmp              2024.2.1          h57928b3_1083    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libblas                   3.9.0              24_win64_mkl    conda-forge
libcblas                  3.9.0              24_win64_mkl    conda-forge
libcurl                   8.10.1               h1ee3ff0_0    conda-forge
libdeflate                1.21                 h2466b09_0    conda-forge
libexpat                  2.6.3                he0c23c2_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              24_win64_mkl    conda-forge
libpng                    1.6.44               h3ca93ac_0    conda-forge
libsodium                 1.0.20               hc70643c_0    conda-forge
libsqlite                 3.46.1               h2466b09_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.7.0                hb151862_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 h013a479_1    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
lz4                       4.3.3           py312h0608a1d_1    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2024.1.0           h66d3029_694    conda-forge
msgpack-python            1.1.0           py312hd5eb7cc_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
mypy                      1.11.2          py312h4389bb4_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nion-alignment            9.3.0                     dev_0    <develop>
nion-dectris-camera       5.2.0                     dev_0    <develop>
niondata                  15.6.3                    dev_0    <develop>
nionswift                 16.11.0                   dev_0    <develop>
nionswift-eels-analysis   0.6.6                     dev_0    <develop>
nionswift-experimental    0.7.13                    dev_0    <develop>
nionswift-instrumentation 23.0.0                    dev_0    <develop>
nionswift-io              15.2.1                    dev_0    <develop>
nionswift-tool            0.4.24                  py312_0    nion
nionswift-usim            5.1.2                     dev_0    <develop>
nionui                    7.1.1                     dev_0    <develop>
nionutils                 4.11.0                    dev_0    <develop>
numcodecs                 0.13.0          py312h72972c8_0    conda-forge
numpy                     1.26.4          py312h8753938_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.3.2                h2466b09_0    conda-forge
pillow                    10.4.0          py312h381445a_1    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
psutil                    6.0.0           py312h4389bb4_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.12.6          hce54a09_1_cpython    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytz                      2024.2             pyhd8ed1ab_0    conda-forge
pyzmq                     26.2.0          py312hd7027bb_2    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
scipy                     1.14.1          py312h1f4e10d_0    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
tbb                       2021.13.0            hc790b64_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
tzlocal                   5.2             py312h2e8e312_1    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
vc                        14.3                h8a93ad2_21    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_21    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_21    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libx11               1.8.9                h0076a8d_1    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1003    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zeromq                    4.3.5                he1f189c_5    conda-forge
zstandard                 0.23.0          py312h7606c53_1    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

I'm using all latest source code from our master branches as of today.

**Comment by Brow71189** [comment]
Never mind, this is just because I was using the latest released nionswift-tool (or nionui-tool). When using the latest CI build of nioni-tool from github, everything works fine.
