### ISSUE TITLE
Workspaces can get internally corrupted, can't create new workspace

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#277]
ND 2019-04-25

Create new workspace doesn't do anything when I click create-error message below.
Probably because I did "next workspace" before, with no next workspace existing.

```
NoneType' object has no attribute 'uuid'
RonchiCam:  [ a:213.75 i:0.00 p:35.34 = 249.09 ]ms           Traceback (most recent call last):
File "C:/NionApps/Miniconda3/envs/developer/Scripts/NionSwiftLauncher\bootstrap.py", line 24, in bootstrap_dispatch
return getattr(object, method_name)(*args)
File "c:\nionapps\developer\master\nionui\nion\ui\QtUserInterface.py", line 874, in clicked
self.on_clicked()
File "c:\nionapps\developer\master\nionui\nion\ui\UserInterface.py", line 941, in handle_clicked
self.on_clicked()
File "c:\nionapps\developer\master\nionswift\nion\swift\Workspace.py", line 623, in accept_button_clicked
accepted_fn(string_edit_widget.text)
File "c:\nionapps\developer\master\nionswift\nion\swift\Workspace.py", line 554, in create_clicked
command = Workspace.CreateWorkspaceCommand(self, text)
File "c:\nionapps\developer\master\nionswift\nion\swift\Workspace.py", line 395, in __init__
self.__workspace_layout_uuid = workspace_controller._workspace.uuid
AttributeError
:
```

**Comment by cmeyer** [comment]
Could not reproduce. Probably fixed when workspaces were reworked around 13cb278b13b1d5106cabfcb6162ab923812ed122. Please re-open if this issue surfaces again.
