### ISSUE TITLE
Shift-clicking in the data panel without selection raises an exception

### ISSUE THREAD

**Issue by sk1p** [nion-software/nionswift#349]
To reproduce, without a selection in the data panel, shift-click on a data item. The following exception is printed on stderr:

```
Traceback (most recent call last):

  File "/home/alex/source/nion/nionui/nion/ui/PyQtProxy.py", line 1850, in mouseReleaseEvent
    self.object.mouseReleased(event.x() // display_scaling, event.y() // display_scaling, event.modifiers())

  File "/home/alex/source/nion/nionui/nion/ui/QtUserInterface.py", line 1450, in mouseReleased
    self.on_mouse_released(x, y, QtKeyboardModifiers(raw_modifiers))

  File "/home/alex/source/nion/nionui/nion/ui/UserInterface.py", line 1940, in handle_mouse_released
    self.on_mouse_released(x, y, modifiers)

  File "/home/alex/source/nion/nionui/nion/ui/CanvasItem.py", line 2739, in __mouse_released
    result = self.__mouse_canvas_item.mouse_released(canvas_item_point.x, canvas_item_point.y, modifiers)

  File "/home/alex/source/nion/nionui/nion/ui/ListCanvasItem.py", line 215, in mouse_released
    return self.__mouse_released(x, y, modifiers, True)

  File "/home/alex/source/nion/nionui/nion/ui/ListCanvasItem.py", line 202, in __mouse_released
    self.__selection.extend(mouse_index)

  File "/home/alex/source/nion/nionutils/nion/utils/Selection.py", line 162, in extend
    if index > self.__anchor_index:


TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

**Comment by cmeyer** [comment]
Fixed https://github.com/nion-software/nionutils/commit/dac8cd8acf2c783a31d67c0f61e661547de82f36
