### ISSUE TITLE
Latest master branch produces lots of errors

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift#360]
Each time the ui gets updated these errors pop up on the terminal.
I'm running from the latest master branch for all repos and nionswift-tool 0.3.23 (Windows 10).

```
File "C:\Users\Andi\Miniconda3\envs\developer\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
File "C:\Users\Andi\Miniconda3\envs\developer\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
File "C:\Users\Andi\Miniconda3\envs\developer\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
File "C:\Users\Andi\Miniconda3\envs\developer\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
File "C:\Users\Andi\Miniconda3\envs\developer\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1913, in __repaint_one
    self.__repaint_layer()
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1951, in __repaint_layer
    traceback.print_stack()
Traceback (most recent call last):
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1946, in __repaint_layer
    self._canvas_item_composition._repaint_finished(self.__layer_drawing_context)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 838, in _repaint_finished
    self._update_container()
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1568, in _update_with_items
    super()._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 779, in _update_with_items
    self._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1573, in _updated
    super()._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 784, in _updated
    self._update_container(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1568, in _update_with_items
    super()._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 779, in _update_with_items
    self._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1573, in _updated
    super()._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 784, in _updated
    self._update_container(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1568, in _update_with_items
    super()._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 779, in _update_with_items
    self._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1573, in _updated
    super()._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 784, in _updated
    self._update_container(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1568, in _update_with_items
    super()._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 779, in _update_with_items
    self._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1573, in _updated
    super()._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 784, in _updated
    self._update_container(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1568, in _update_with_items
    super()._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 779, in _update_with_items
    self._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1573, in _updated
    super()._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 784, in _updated
    self._update_container(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1568, in _update_with_items
    super()._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 779, in _update_with_items
    self._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1573, in _updated
    super()._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 784, in _updated
    self._update_container(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1568, in _update_with_items
    super()._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 779, in _update_with_items
    self._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1573, in _updated
    super()._updated(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 784, in _updated
    self._update_container(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 793, in _update_container
    container._update_with_items(canvas_items)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1567, in _update_with_items
    if self.__layout_render_trait and not self.__layout_render_trait._try_update_with_items(canvas_items):
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 2624, in _try_update_with_items
    self._canvas_item_composition.canvas_widget.draw_section(section_id, drawing_context, canvas_rect)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\UserInterface.py", line 2093, in draw_section
    self._behavior.draw_section(section_id, drawing_context, canvas_rect)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\QtUserInterface.py", line 1412, in draw_section
    self.proxy.Canvas_drawSection_binary(self.widget, section_id, drawing_context.binary_commands, drawing_context.images, canvas_rect.left, canvas_rect.top, canvas_rect.width, canvas_rect.height)
File "C:/Users/Andi/Miniconda3/envs/developer/Scripts/NionSwiftLauncher\bootstrap.py", line 34, in _missing
    return getattr(self.__nion_lib, name)(*args, **kwargs)
AttributeError: module 'HostLib' has no attribute 'Canvas_drawSection_binary'
File "C:\Users\Andi\Miniconda3\envs\developer\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
File "C:\Users\Andi\Miniconda3\envs\developer\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
File "C:\Users\Andi\Miniconda3\envs\developer\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
File "C:\Users\Andi\Miniconda3\envs\developer\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
File "C:\Users\Andi\Miniconda3\envs\developer\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1913, in __repaint_one
    self.__repaint_layer()
File "c:\cygwin64\home\andi\git\nionui\nion\ui\CanvasItem.py", line 1951, in __repaint_layer
    traceback.print_stack()

```

**Comment by Brow71189** [comment]
Updating to the latest `nionswift-tool` (0.4.1) gets rid of the errors.
