### ISSUE TITLE
Pending computations should be canceled if input or computation removed

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift#518]
Two potential race conditions exist:

1) an object input used in the execute phase is removed
2) the computation is removed between the execute and commit phase

**Comment by cmeyer** [comment]
Stack trace

```
Traceback (most recent call last):
File "/Users/cmeyer/Library/Developer/Xcode/DerivedData/NionUILauncher-cvaiafllwuzpmbfrjrdxnixtstud/Build/Products/Release/Nion UI Launcher.app/Contents/MacOS/../Resources/bootstrap.py", line 24, in bootstrap_dispatch
return getattr(object, method_name)(*args)
File "/Users/cmeyer/Developer/Nion/MasterProject/nionui/nion/ui/QtUserInterface.py", line 1862, in periodic
self._handle_periodic()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionui/nion/ui/UserInterface.py", line 2906, in _handle_periodic
self.on_periodic()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/DocumentController.py", line 357, in periodic
super().periodic()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionui/nion/ui/Window.py", line 300, in periodic
self.__periodic_queue.perform_tasks()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionutils/nion/utils/Process.py", line 29, in perform_tasks
task()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/DocumentController.py", line 120, in call_soon
self.document_model.perform_call_soon()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/model/DocumentModel.py", line 793, in perform_call_soon
fn()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/model/DocumentModel.py", line 1614, in perform_data_item_merge
pending_data_item_merge_fn()
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift-eels-analysis/nionswift_plugin/nion_eels_analysis/BackgroundSubtraction.py", line 41, in commit
self.computation.set_referenced_xdata("background", self.__background_xdata)
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/Facade.py", line 2288, in set_referenced_xdata
data_item = self.get_result(name)
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/Facade.py", line 2257, in get_result
result = self.__computation.get_output(name)
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/model/Symbolic.py", line 1649, in get_output
for result in self.results:
File "/Users/cmeyer/Developer/Nion/MasterProject/nionswift/nion/swift/model/Persistence.py", line 855, in __getattr__
raise AttributeError("%r object has no attribute %r" % (self.__class__, name))
AttributeError
:
<class 'nion.swift.model.Symbolic.Computation'> object has no attribute 'results'
```

**Comment by cmeyer** [comment]
Haven't seen this in a while. Closing.
